* Get Clear

- [ ] Collect loose papers and materials
  Gather all accumulated business cards, receipts, and miscellaneous
  paper-based materials into your in-tray.

- [ ] Get **IN** to zero
  Process completely all outstanding paper materials, journal and
  meeting notes, voicemails, dictation, and emails.
  - [ ] Paper materials
  - [ ] Journal & Meeting Notes
  - [ ] Voicemails & Dictation
  - [ ] Emails
  - [ ] Slack saved messages
  - [ ] Browser Tabs
  - [ ] Downloads folder

- [ ] Empty your head
  Put in writing and process any uncaptured new projects, action
  items, waiting fors, someday/maybes, etc.

- [ ] Clear off my desk

- [ ] Process GTD Inbox to zero

* Get Current

- [ ] Review my **Next Actions** list
  Mark off completed actions. Review for reminders of further action
  steps to record.

- [ ] Review previous calendar data
  Review past calendar in detail for remaining action items, reference
  data, etc., and transfer into the active system.

- [ ] Review upcoming calendar
  Review upcoming calendar events - long and short term. Capture
  actions triggered.

- [ ] Review my **Waiting For** list and email folder
  Record appropriate actions for any needed follow-up. Check off
  received ones.

- [ ] Review project (and larger outcome) lists
  Evaluate status of projects, goals, and outcomes, one by one,
  ensuring at least one current next action item on each. Browse
  through project plans, support material, and any other
  work-in-progress material to trigger new actions, completions,
  waiting fors, etc.

* Get creative

- [ ] Review someday/maybe list
  Review for any projects or actions which may now have become active,
  and transfer to the appropriate list.
  Delete items no longer of interest.

- [ ] Be creative & courageous
  Any new, wonderful, hare-brained, creative, thought-provoking,
  risk-taking ideas to add into your system?

* Post-Review

** What went well this week?

** What could be adjusted

- [ ] Create tasks to adjust these items

** What should I stop doing?

** What should I start doing?

- [ ] Create a task to plan these items in more detail
